ftp:
  host: 192.168.241.152:21
  username: webgis
  password: webgis
  filepath: /upload/image/
  localpath: /temp/
  serverpath: http://192.168.241.152:84/webgis
spring:
  datasource:
    url: jdbc:mysql://192.168.241.192:3306/bike?useUnicode=true&characterEncoding=utf8
    username: bike
    password: bike
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cluster:
      nodes: 192.168.57.249:7000,192.168.57.249:7001,192.168.57.249:7002
      password:
  data:
    mongodb:
      host: 192.168.240.221
      port: 27018
      database: webgis
      username: webgis
      password: tmkjzgb123
  kafka:
    brokers: 192.168.57.249:9092
    zookeepers: 192.168.57.249:2181
  netty:
    tcpPort: 12345
    bossThreadCount: 2
    workerThreadCount: 2
    soKeepalive: true
    soBacklog: 100
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.57.249:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
