ftp:
  host: 192.168.241.152:21
  username: webgis
  password: webgis
  filepath: /upload/excel/
  localpath: /temp/
download:
  host: 192.168.241.152:84/webgis
spring:
  datasource:
    url: jdbc:mysql://192.168.241.192:3306/bikelog?useUnicode=true&characterEncoding=utf8
    username: bikelog
    password: bikelog
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cluster:
      nodes: 192.168.57.249:7000,192.168.57.249:7001,192.168.57.249:7002
      password:
  kafka:
    brokers: 192.168.57.249:9092
    zookeepers: 192.168.57.249:2181
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.242.8:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false